reward_healer = {
    "damageEnemyStatue": 1,
    "damageEnemyUnit": 0.5,
    "killEnemyStatue": 16,
    "killEnemyUnit":2,
    "healFriendlyStatue":6,
    "healTeammate1":5,
    "healTeammate2":5,
    "timeSpentHomeBase":0,
    "timeSpentHomeTerritory":0,
    "timeSpentAwayTerritory":0,
    "timeSpentAwayBase":-2,
    "damageTaken":-8,
    "friendlyFire":-7,
    "healEnemy":-10,
    "fallDamageTaken":-10,
    "statueDamageTaken":-9,
    "teamSpirit":0,
    "timeScaling":1
}

"""reward_healer = {
    "damageEnemyStatue": 2,
    "damageEnemyUnit": 1,
    "killEnemyStatue": 5,
    "killEnemyUnit":2,
    "healFriendlyStatue":3,
    "healTeammate1":4,
    "healTeammate2":4,
    "timeSpentHomeBase":0,
    "timeSpentHomeTerritory":0,
    "timeSpentAwayTerritory":0,
    "timeSpentAwayBase":-2,
    "damageTaken":-2,
    "friendlyFire":-1,
    "healEnemy":-4,
    "fallDamageTaken":-2,
    "statueDamageTaken":-1,
    "teamSpirit":0,
    "timeScaling":1
}"""